security:
    encoders:
        AppBundle\Entity\Abonne:
            algorithm: plaintext

    providers:
        classique_web:
            entity:
                class: AppBundle:Abonne
                property: login

    firewalls:
    

        main:
            anonymous:  ~
            form_login:
                login_path: login
                check_path: login

            pattern:    ^/
            http_basic: ~
            provider: classique_web
